---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Set timezone to Central US
  timezone:
    name: "{{ timezone }}"
  notify: restart rsyslog

- name: Install required packages
  apt:
    name:
      - curl
      - wget
      - ca-certificates
      - gnupg
      - lsb-release
      - make
    state: present